services:
  tou-document-parser:
    build: .
    container_name: tou-document-parser
    restart: unless-stopped
    ports:
      - "5040:5040"
    volumes:
      - ./uploads:/app/uploads
    environment:
      - TESSDATA_PREFIX=/usr/share/tesseract-ocr/5/tessdata/
      - FLASK_ENV=production
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
