name: tou_document_parser
description: "Flutter Web App to upload and classify documents."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.5.0
  file_picker: ^10.3.3
  web: ^1.1.1

  flutter_bloc: ^9.1.1
  freezed_annotation: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.10.0
  freezed: ^3.2.3

flutter:
  uses-material-design: true
  assets:
    - assets/
